.TH VENTO 1 "June 2024" "1.0" "Vento Manual"
.SH NAME
vento \- a simple text editor

.SH SYNOPSIS
.B vento
.RI [ options ] " [file]"

.SH DESCRIPTION
.B Vento
is a simple text editor with basic features such as loading, saving, and creating files. It also includes a status bar, a help screen, and a scroll bar.

.SH OPTIONS
.TP
.B \-h, \-\-help
Show the help screen.

.SH USAGE
.B vento
[optional-filename]

.SH FEATURES
.IP \[bu] 2
Basic editor functionality
.IP \[bu] 2
Load files
.IP \[bu] 2
Save as
.IP \[bu] 2
Status bar
.IP \[bu] 2
Create new file
.IP \[bu] 2
Scroll bar
.IP \[bu] 2
Help screen
.IP \[bu] 2
Save feature (as opposed to save as)

.SH PLANNED FEATURES
.IP \[bu] 2
Undo and redo
.IP \[bu] 2
Syntax highlighting
.IP \[bu] 2
Support for multiple files
.IP \[bu] 2
Spell checker support
.IP \[bu] 2
Copy and paste
.IP \[bu] 2
Git integration
.IP \[bu] 2
Menu system
.IP \[bu] 2
Customizable configuration
.IP \[bu] 2
Command to delete the current line

.SH AUTHOR
The Vento Team

.SH COPYRIGHT
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH LICENSE
Vento is licensed under the GNU General Public License v3.0. You may obtain a copy of the GNU General Public License at <https://www.gnu.org/licenses/gpl-3.0.html>.
