.TH VENTO 1 "August 2024" "0.1.3" "Vento Manual"
.SH NAME
vento \- a simple text editor
.SH SYNOPSIS
.B vento
.RI [ options ] " [file...]"
.SH DESCRIPTION
.B Vento
is a lightweight terminal based text editor focused on simplicity.  It supports editing multiple files at once, customizable color themes, optional line numbers and full mouse interaction.  A status bar shows the current line and column, and a scroll bar indicates your position in the document.  Basic syntax highlighting is provided for C, HTML and Python.  Files can be loaded from the command line or through a file dialog and a menu system exposes common actions.
.SH SYSTEM REQUIREMENTS
A POSIX compatible system with a C compiler, binutils and the ncurses development libraries is required to build Vento.  On Debian based distributions install \fBbuild-essential\fP and \fBlibncursesw5-dev\fP.
Vento has been tested on Linux and macOS and should also build on BSD derivatives and other POSIX-compliant platforms.
.SH OPTIONS
.TP
.BR \-h , \-\-help
Display the help screen and exit.
.SH CONFIGURATION
User preferences are stored in \fI~/.ventorc\fP.  The file is created automatically if it does not exist.  Recognized keys include:
.IP \[bu] 2
background_color, keyword_color, comment_color, string_color, type_color, symbol_color
.IP \[bu] 2
theme \- base name of a file in the \fBthemes\fP directory
.IP \[bu] 2
enable_color \- enable or disable colored output
.IP \[bu] 2
enable_mouse \- toggle mouse input
.IP \[bu] 2
show_line_numbers \- display line numbers in the editor
.PP
Configuration options can also be changed interactively using the \fBFile\fP \-> \fBSettings\fP dialog which writes updates back to \fI~/.ventorc\fP.
.SH KEYBOARD SHORTCUTS
.TP
.B CTRL-S
Save the current file
.TP
.B CTRL-O
Open the Save As dialog
.TP
.B CTRL-L
Open a file dialog
.TP
.B CTRL-F
Search for text
.TP
.B CTRL-R
Replace text
.TP
.B CTRL-Z
Undo the last action
.TP
.B CTRL-Y
Redo the last undone action
.TP
.B F6 , F7
Switch between open files
.PP
Press \fBCTRL-H\fP to view all shortcuts.
.SH EXAMPLES
.TP
Start the editor with no file
.B vento
.TP
Edit an existing file
.B vento example.txt
.TP
Save your changes
Press \fBCTRL-S\fP
.TP
Use the default theme by setting \fBtheme=default\fP in \fI~/.ventorc\fP then run
.B vento
.SH PLANNED FEATURES
.IP \[bu] 2
Spell checker support
.IP \[bu] 2
Git integration
.IP \[bu] 2
Macro support
.IP \[bu] 2
Extensions API
.SH AUTHOR
Stephen Planck - splanck@tutamail.com
.SH COPYRIGHT
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH LICENSE
Vento is licensed under the GNU General Public License v3.0. You may obtain a copy of the GNU General Public License at <https://www.gnu.org/licenses/gpl-3.0.html>.
